// GENERATED by gen.py from dimensions.json - do not edit by hand.
// Units: mm, g, deg.  Frame: origin at Roomba centre on the floor, +Y forward, +Z up.

// ---- roomba_690 ----
roomba_690_diameter = 329.9;
roomba_690_height = 92.25;
roomba_690_clean_button_diameter = 40;
roomba_690_clean_button_center = [0, 0];
roomba_690_dustbin_release_center = [0, -120];
roomba_690_minidin_position = [118, -95, 60];
roomba_690_minidin_note = "rear right, beneath a snap-away guard (OI spec p.3)";
roomba_690_wheel_track = 235;
roomba_690_wheel_diameter = 72;
roomba_690_caster_position = [0, 120];
roomba_690_screw_bosses = [[30, 127], [-30, 127], [109, 88], [-109, 88], [76, 50.46], [-76, 50.46], [51.82, -66], [-51.82, -66], [0, -78], [113.5, -78], [-113.5, -78]];
roomba_690_screw_bosses_note = "OI spec p.6 'Internal Screw Boss Locations', read at 2.4x zoom. Under the faceplate; take #4-40 or M3 standoffs. +Y forward.";
roomba_690_mass_g = 3500;
roomba_690_bumper_diameter = 348.5;
roomba_690_height_rear = 82.94;
roomba_690_deck_height = 82.94;
roomba_690_shell_underside_measured = 10.9;
roomba_690_deck_flat_y_max = 144;
roomba_690_front_ir_boss_center = [0, 156];
roomba_690_front_ir_boss_w = 16;
roomba_690_front_ir_boss_d = 18;
roomba_690_front_ir_boss_z_top = 90.94;

// ---- jetson_xavier_nx_devkit ----
jetson_xavier_nx_devkit_board_w = 100;
jetson_xavier_nx_devkit_board_d = 79;
jetson_xavier_nx_devkit_board_t = 1.57;
jetson_xavier_nx_devkit_mount_holes = [[3.8, 75.8], [96.4, 75.8], [3.8, 18.4], [96.4, 18.4]];
jetson_xavier_nx_devkit_mount_hole_d = 3.2;
jetson_xavier_nx_devkit_module_w = 69.6;
jetson_xavier_nx_devkit_module_d = 45.0;
jetson_xavier_nx_devkit_module_offset = [16, 22];
jetson_xavier_nx_devkit_heatsink_h = 18.0;
jetson_xavier_nx_devkit_fan_d = 34.5;
jetson_xavier_nx_devkit_fan_h = 8.25;
jetson_xavier_nx_devkit_stack_height = 34.66;
jetson_xavier_nx_devkit_barrel_jack_od = 5.5;
jetson_xavier_nx_devkit_barrel_jack_pin = 2.5;
jetson_xavier_nx_devkit_barrel_jack_polarity = "centre positive";
jetson_xavier_nx_devkit_barrel_jack_v_in = [9, 20];
jetson_xavier_nx_devkit_barrel_jack_i_max = 3.5;
jetson_xavier_nx_devkit_mass_g = 300;
jetson_xavier_nx_devkit_connector_h = 19.38;
jetson_xavier_nx_devkit_underside_h = 3.08;
jetson_xavier_nx_devkit_envelope_w = 103;
jetson_xavier_nx_devkit_envelope_d = 90.5;
jetson_xavier_nx_devkit_mount_holes_note = "outer corner holes of the 100x79 PCB, read from fig 4-1 at 2.4x zoom (+/-0.5 mm); pattern 92.6 x 57.4";
jetson_xavier_nx_devkit_module_below_pcb = 1.4;
jetson_xavier_nx_devkit_module_above_pcb = 4.2;
jetson_xavier_nx_devkit_underside_note = "3.08 mm is the component height BELOW the carrier PCB, not a socket gap (carrier spec Figure 4-1).";
jetson_xavier_nx_devkit_module_socket_gap = 6.69;
jetson_xavier_nx_devkit_stack_above_board = 30.01;
jetson_xavier_nx_devkit_heatsink_w = 57.8;
jetson_xavier_nx_devkit_heatsink_d = 39.0;
jetson_xavier_nx_devkit_fan_recessed = true;

// ---- realsense_d435i ----
realsense_d435i_w = 90;
realsense_d435i_h = 25;
realsense_d435i_d = 25;
realsense_d435i_mass_g = 75;
realsense_d435i_mount_m3_holes = 2;
realsense_d435i_mount_m3_spacing = 45;
realsense_d435i_mount_m3_max_insertion = 3;
realsense_d435i_mount_bolt = "M3 x 6 through a 4 mm plate";
realsense_d435i_mount_tripod = "1/4-20 UNC";
realsense_d435i_mount_torque_nm = 0.4;
realsense_d435i_usb = "USB-C, rear face";
realsense_d435i_lens_offsets_x = [-25, -10, 10, 25];

// ---- ovonic_3s_8000 ----
ovonic_3s_8000_l = 135;
ovonic_3s_8000_w = 42;
ovonic_3s_8000_h = 34;
ovonic_3s_8000_corner_r = 3;
ovonic_3s_8000_mass_g = 424;
ovonic_3s_8000_chemistry = "3S LiPo";
ovonic_3s_8000_connectors_main = "Deans T-plug";
ovonic_3s_8000_connectors_balance = "JST-XHR-4P";
ovonic_3s_8000_design_l = 141.95;
ovonic_3s_8000_design_w = 45.25;
ovonic_3s_8000_design_h = 34;

// ---- drok_buck ----
drok_buck_l = 65.6;
drok_buck_w = 40;
drok_buck_h = 25;
drok_buck_mass_g = 59;

// ---- bms_daier_3s ----
bms_daier_3s_l = 56;
bms_daier_3s_w = 45;
bms_daier_3s_t = 1.2;
bms_daier_3s_clearance_h = 6;
bms_daier_3s_mass_g = 12;
bms_daier_3s_balance_style = "solder_pads";
bms_daier_3s_pads_Bminus = [6.5, 4.9, 10.5, 11.3];
bms_daier_3s_pads_B1 = [52.9, 5.1, 9.9, 11.8];
bms_daier_3s_pads_Bplus = [53.2, 42.1, 8.7, 10.8];
bms_daier_3s_pads_B2 = [5.2, 41.4, 11.3, 13.1];
bms_daier_3s_pads_round_Pplus = [51.9, 28.9, 10.2];
bms_daier_3s_pads_round_Pminus = [51.8, 19.0, 9.4];
bms_daier_3s_mosfet_bank = [30, 17, 22, 15, 2.0];
bms_daier_3s_ic_row = [30, 40, 30, 6, 1.7];
bms_daier_3s_current_a_cont = 25;
bms_daier_3s_current_a_peak = 40;

// ---- ina219_hiletgo ----
ina219_hiletgo_l = 25.5;
ina219_hiletgo_w = 22.3;
ina219_hiletgo_t = 1.6;
ina219_hiletgo_mass_g = 3;

// ---- fuse_holder_inline ----
fuse_holder_inline_l = 45;
fuse_holder_inline_w = 20;
fuse_holder_inline_h = 22;
fuse_holder_inline_mass_g = 20;
fuse_holder_inline_cap_w = 21.8;
fuse_holder_inline_body_len = 30.5;
fuse_holder_inline_lead_len = 299.7;
fuse_holder_inline_fuse_w = 19.1;
fuse_holder_inline_fuse_h = 19.1;

// ---- home_base ----
home_base_w = 149;
home_base_d = 159;
home_base_h = 114;
home_base_ramp_h = 18;
home_base_ramp_d = 75;
home_base_stock_contact_spacing = 80;
home_base_mass_g = 400;
home_base_ramp_plate_t = 3;
home_base_ramp_d_range = [60, 90];
home_base_ramp_h_range = [15, 22];
home_base_ramp_angle_deg = 13.5;
home_base_stock_contact_spacing_range = [70, 90];

// ---- pogo_p75_b1 ----
pogo_p75_b1_d = 1.02;
pogo_p75_b1_body_d = 1.36;
pogo_p75_b1_l = 16.5;
pogo_p75_b1_travel = 2.5;
pogo_p75_b1_i_max = 3;
pogo_p75_b1_body_len = 12.9;
pogo_p75_b1_tip_len = 3.6;

// ---- contact_geometry ----
contact_geometry_pad_w = 35;
contact_geometry_pad_d = 20;
contact_geometry_pad_gap = 15;
contact_geometry_group_spacing = 50;
contact_geometry_pins_per_pad = 2;
contact_geometry_pin_pitch_in_group = 6;
contact_geometry_working_tolerance = 14.5;
contact_geometry_short_threshold = 29.5;
contact_geometry_pin_compression = 1.5;

// ---- print ----
print_wall = 2.4;
print_floor = 2.0;
print_m3_clearance_d = 3.4;
print_m3_tap_d = 2.5;
print_m3_heatset_d = 4.0;
print_m3_head_d = 6.0;
print_standoff_od = 7;
print_fit_clearance = 0.4;
print_strap_slot = [22, 3];

// ---- layout ----
layout_jetson_center = [104, 0];
layout_jetson_rotation = 90;
layout_battery_center = [-88, 0];
layout_battery_rotation = 90;
layout_camera_pivot = [0, 130];
layout_camera_tilt_deg = -8;
layout_drok_center = [0, 86];
layout_pads_center_y = 100;
layout_pads_z = 0;
layout_chassis_clearance = 8;
layout_drok_rotation = 180;
layout_carrier_angles = [0, 90, 180];

// ---- frame ----
frame_hub_od = 76;
frame_hub_id = 60;
frame_hub_t = 6;
frame_hub_pad_w = 24;
frame_hub_pad_r1 = 53;
frame_hub_hole_r = [40, 49];
frame_hub_nut_af = 5.5;
frame_hub_nut_h = 2.4;
frame_carrier_plate_t = 4;
frame_carrier_tongue_w = 24;
frame_carrier_tongue_r0 = 32;
frame_carrier_tongue_r1 = 52;
frame_carrier_tongue_t = 4;
frame_carrier_ramp_r1 = 62;
frame_carrier_boss_tab_w = 16;
frame_carrier_corner_r = 6;
frame_jetson_r0 = 62;
frame_jetson_r1 = 148;
frame_jetson_half_w = 60;
frame_jetson_standoff_h = 6;
frame_jetson_vent = [30, 58];
frame_jetson_boss_tabs = [[76, 50.46, 76, 50.46], [113.5, -78, 110, -60]];
frame_battery_r0 = 62;
frame_battery_wall = 3;
frame_battery_floor = 2.5;
frame_battery_wall_h = 34;
frame_battery_lid_t = 2.5;
frame_battery_lid_skirt = 6;
frame_battery_strap_slot = [22, 3];
frame_battery_boss_tabs = [[109, -88, 109, -68], [51.82, 66, 68, 66]];
frame_battery_bms_center_y = -30;
frame_battery_ina_center_y = 30;
frame_battery_outer = [52, 149];
frame_battery_lid_lip = 2.5;
frame_front_r0 = 62;
frame_front_r1 = 144;
frame_front_half_w = 58;
frame_front_boss_tabs = [[127, -30, 127, -30], [127, 30, 127, 30]];
frame_front_drok_center_y = 86;
frame_camera_pivot_y = 130;
frame_camera_pivot_z = 27.06;
frame_camera_cheek_t = 4;
frame_camera_cheek_x = 54;
frame_camera_cheek_y = [108, 144];
frame_camera_cheek_top = 33.06;
frame_camera_rocker = [88, 24, 4];
frame_camera_ear_t = 8;
frame_camera_ear_x = 45.5;
frame_camera_ear_top = 32.06;
frame_camera_lock_offset = [-9, -13.5];
frame_camera_lock_d = 3.4;
frame_camera_tilt_min = -25;
frame_camera_tilt_max = 15;
frame_camera_tripod_clearance_d = 6.8;
frame_dock_block = [130, 28, 6];
frame_pin_hole_d = 1.6;
frame_pin_proud = 4.5;
frame_pad_carrier = [120, 28, 3.5];
frame_pad_pocket_depth = 1.2;
frame_fr4_t = 1.6;
frame_ziptie_slot = [4.5, 2.2];

// ---- dc_pigtail ----
dc_pigtail_barrel_od = 10.0;
dc_pigtail_sleeve_od = 5.5;
dc_pigtail_pin_id = 2.5;
dc_pigtail_shell_len = 10.8;
dc_pigtail_plug_len = 32.0;
dc_pigtail_cable_od = 5.0;
dc_pigtail_cable_len = 300.0;

// ---- ports ----
ports_drok_in_plus = [10, 33.4, 18];
ports_drok_in_minus = [-10, 33.4, 18];
ports_drok_out_plus = [10, -33.4, 18];
ports_drok_out_minus = [-10, -33.4, 18];
ports_ina219_header_x = -8.15;
ports_ina219_header_y0 = -6.775;
ports_ina219_header_pitch = 2.54;
ports_ina219_header_z = 3.26;
ports_lipo_t_plus = [-67.6, -8, 17];
ports_lipo_t_minus = [-67.6, 8, 17];
ports_lipo_balance_first = [-67.6, -3.75, 6];
ports_lipo_balance_pitch = 2.5;
ports_jetson_barrel = [-34.5, 41.5, 7];
ports_jetson_barrel_neg = [-34.5, 43.5, 3.5];
ports_jetson_usb_upper = [15, 41, 14];
ports_jetson_usb_lower = [15, 41, 6];
ports_jetson_header_pin1 = [-38, -37.3, 10];
ports_jetson_header_pitch = 2.54;
ports_jetson_header_row_gap = 2.54;
ports_camera_usb_c = [28, -13.5, -2];
ports_pad_carrier_lead_plus = [25, -11, 3.6];
ports_pad_carrier_lead_minus = [-25, -11, 3.6];
ports_loom_deck_grommet = [46, 48, 82.94];
ports_loom_fuse_mount = [-40, -58, 86];
ports_loom_switch_mount = [0, -62, 86];
ports_loom_camera_lane = [40, 100];
