#!/usr/bin/env python3
"""Emit hardware/dims.scad from hardware/dimensions.json.

Every top-level object becomes a prefix, nested keys join with '_', arrays
become OpenSCAD vectors. Keys starting with '_' are documentation and skipped.

    {"roomba_690": {"diameter": 330}}  ->  roomba_690_diameter = 330;
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "dimensions.json")
OUT = os.path.join(HERE, "dims.scad")


def scad_value(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return '"' + v.replace('"', '\\"') + '"'
    if isinstance(v, list):
        return "[" + ", ".join(scad_value(x) for x in v) + "]"
    raise TypeError(f"unsupported value {v!r}")


def flatten(prefix, obj, out):
    for k, v in obj.items():
        if k.startswith("_"):
            continue
        name = f"{prefix}_{k}" if prefix else k
        if isinstance(v, dict):
            flatten(name, v, out)
        else:
            out.append((name, v))


def main():
    with open(SRC) as f:
        data = json.load(f)
    lines = ["// GENERATED by gen.py from dimensions.json - do not edit by hand.",
             "// Units: mm, g, deg.  Frame: origin at Roomba centre on the floor, +Y forward, +Z up.",
             ""]
    for section, body in data.items():
        if section.startswith("_"):
            continue
        rows = []
        flatten(section, body, rows)
        lines.append(f"// ---- {section} ----")
        for name, v in rows:
            if v is None:
                continue          # unknown, deliberately not exported
            lines.append(f"{name} = {scad_value(v)};")
        lines.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}: {sum(1 for l in lines if ' = ' in l)} values")


if __name__ == "__main__":
    sys.exit(main())
